# Generated by Django 2.2.5 on 2021-03-21 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clas', models.CharField(max_length=264)),
                ('name', models.CharField(max_length=264)),
                ('city', models.CharField(max_length=264)),
            ],
        ),
    ]
